name: Compile Examples

on:
  push:
    paths-ignore:
      - '.github/workflows/cpp_lint.yml'
      - '.github/workflows/compile_library.yml'
  pull_request:
    paths-ignore:
      - '.github/workflows/cpp_lint.yml'
      - '.github/workflows/compile_library.yml'

jobs:
  esp8266:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example: 
        - "examples/Authentications/LegacyTokenAuthen/LegacyTokenAuthen.ino"
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Install 3rd party dependecies
      run: | 
        pio lib install \
        https://github.com/mobizt/Firebase-ESP-Client
        
    - name: update library
      run: |
        pio lib --global update

    - name: Run PlatformIO Examples
      run: |
        pio ci --board=d1_mini 
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}
